### PR TITLE
Updated admin widgets

### PR DESCRIPTION
**Pull request by w33zy**
Adds the ````rpr_recipe```` post type to the default WP admin dashboard widgets.

### CODE REVIEW

**Comment by jckoester** [comment]
Just two questions:
- Why did you put that code into the public class? As only the admin dashboard in the backend is effect I believe this should be part of the admin class.
- Why do you change the query so much? With the changes you made, recipes won't appear on the frontpage of the blog anymore, even if the option is set.

**Comment by w33zy** [comment]
When deciding where to put the functions I looked at the admin class functions and saw that they were mostly concerned with saving the custom post meta such as ingredients and directions.
I then looked at the public class and saw that it dealt with UI functions such as adding recipes to the list of posts. So I went with the public class.

The only change to the query this PR made is adding recipes to the query when the ````dashboard_recent_posts_query_args```` fires. The other edits I made to the public is adjusting the tab formatting of some of the functions I had difficulty reading because of the formatting. Also, on my setup, the new changes does not affect the visibility of recipes on the frontpage

**Comment by jckoester** [comment]
Alright, so this is a misunderstanding. The public class is only dealing with rendering, querying, etc for all publicly available parts of the page. The admin class is doing rendering, querying, saving, editing, migrating, options and so on for the backend part available only to authors and aministrators. So the dashboard widget needs to go there.

The query function you've changed is actually changing the wordpress main query to include the recipe post type on certain pages. Changing this can have a lot of unwanted effects, espacially in conjunction with other plugins.
There is no need to change the query for admin pages, that's why this function is limited to public.
To get the data for the dashboard widget you should start a new query in the admin class.

**Comment by w33zy** [comment]
So you are saying i should just those 2 functions to the ````rpr-admin.php```` class?

**Comment by jckoester** [comment]
Yes. That's pretty much it.
I'd actuall prefer another icon in front of the recipes count, but that's something I can do later.

**Comment by w33zy** [comment]
OK, I thought I needed to wrap the function in ````is_admin()````.

I used that icon for the sake of consistency and branding.

**Comment by jckoester** [comment]
That's not wrong either.
It's just that I like to keep my functions in separate places.

For the same reason I'd have used a grey version of the plugin's logo. The same like in front of recipes in the sidebar.

**Comment by w33zy** [comment]
Check again, I am using that 'logo_16x16.png' file for the icon.

**Comment by jckoester** [comment]
That's what I'd been using as well. I guess I got mislead by the screenshot you've shown. There the logo was a circle.

**Comment by jckoester** [comment]
OK, great. Will pull that in for 0.9.0

**Pull request merged**
